<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/


// User routes...
Route::resource('user', 'UserController');
/*// User Additional Info routes...
Route::resource('user-additional-info', 'UserAdditionalInfoController');
// User Shipping Info routes...
Route::resource('user-shipping-info', 'UserShippingInfoController');
// Social Site routes...
Route::resource('social-site', 'SocialSiteController');
// User Social Account Info routes...
Route::resource('user-social-account-info', 'UserSocialAccountInfoController');
// UserLanguage routes...
Route::resource('user-language', 'UserLanguageController');*/

// Influencer routes...
Route::resource('influencer', 'InfluencerController');

// User profile routes
Route::prefix('profile')->name('profile-')->group(function () {
    // User Account Info routes...
    Route::resource('account-info', 'Profile\AccountInfoController');
    // User Additional Info routes...
    Route::resource('additional-info', 'Profile\AdditionalInfoController')->only(['index', 'update']);
    // User Shipping Info routes...
    Route::resource('shipping-info', 'Profile\ShippingInfoController')->only(['index', 'update']);
    // User Social Account routes...
    Route::resource('social-account-info', 'Profile\UserSocialAccountInfoController')->only(['index', 'update']);
    // User Language routes...
    //Route::resource('language', 'Profile\LanguageController');
    // Change Password routes...
    Route::resource('password-change', 'Profile\PasswordChangeController');
});
// Role routes...
// Route::resource('role', 'RoleController');
// Permission routes...
// Route::resource('permission', 'PermissionController');
